window.CAPTIONS = 
[
  { "start": 0.24, "end": 3.99, "en": "hello good morning", "vi": "xin chào buổi sáng" },
  { "start": 4.07, "end": 5.83, "en": "good afternoon and good evening", "vi": "buổi chiều và buổi tối tốt lành" },
  { "start": 5.83, "end": 9.08, "en": "it's another day and today", "vi": "lại là một ngày mới và hôm nay" },
  { "start": 9.3, "end": 13.92, "en": "is Monday and I'm lazy as f*** today", "vi": "là thứ Hai và hôm nay mình lười kinh khủng" },
  { "start": 13.92, "end": 17.4, "en": "no I mean I'm lazy as f***", "vi": "không ý mình là mình lười quá chừng" },
  { "start": 17.41, "end": 22.67, "en": "recently I don't know the reason why I'm still doing the work", "vi": "gần đây mình không biết lý do tại sao mình vẫn làm công việc này" },
  { "start": 22.68, "end": 26, "en": "the qualities of the work is not that bad", "vi": "chất lượng công việc thì không đến nỗi tệ" },
  { "start": 26, "end": 28.84, "en": "but I don't feel like I'm fulfilled", "vi": "nhưng mình không cảm thấy mãn nguyện" },
  { "start": 28.87, "end": 33.52, "en": "I don't feel like I have motivations to do the work", "vi": "mình không cảm thấy mình có động lực để làm việc" },
  { "start": 33.52, "end": 38.12, "en": "I don't feel like I want to be the part of that job anymore", "vi": "mình không cảm thấy muốn là một phần của công việc đó nữa" },
  { "start": 38.35, "end": 41.64, "en": "at the beginning everything is great", "vi": "lúc đầu mọi thứ đều tuyệt vời" },
  { "start": 41.64, "end": 47.79, "en": "I'm enthusiastic I push a lot", "vi": "mình rất nhiệt huyết, mình nỗ lực rất nhiều" },
  { "start": 47.79, "end": 53.39, "en": "of things I do a lot of challenge stuff", "vi": "mình làm rất nhiều thứ thử thách" },
  { "start": 53.39, "end": 57.18, "en": "but later on I feel empty", "vi": "nhưng sau đó mình cảm thấy trống rỗng" },
  { "start": 57.22, "end": 63.91, "en": "I think it's life sometimes it's tough to push you out of your comfort zone", "vi": "mình nghĩ đó là cuộc sống đôi khi thật khó để đẩy bạn ra khỏi vùng an toàn" },
  { "start": 63.91, "end": 69.18, "en": "but as long as you stay you'll become addicted to the comfort zone", "vi": "nhưng chừng nào bạn còn ở lại bạn sẽ trở nên nghiện vùng an toàn" },
  { "start": 69.21, "end": 74.49, "en": "and you don't want to push yourself outside of that zone", "vi": "và bạn không muốn đẩy bản thân ra khỏi vùng đó" },
  { "start": 74.49, "end": 80.19, "en": "so you become as normal as usual at other people", "vi": "vì vậy bạn trở nên bình thường như bao người khác" },
  { "start": 80.19, "end": 83.64, "en": "but if you dare to step outside your comfort zone", "vi": "nhưng nếu bạn dám bước ra khỏi vùng an toàn của mình" },
  { "start": 83.64, "end": 91.12, "en": "everything change your work your view your everything will change completely", "vi": "mọi thứ thay đổi công việc, góc nhìn, mọi thứ của bạn sẽ hoàn toàn thay đổi" },
  { "start": 91.12, "end": 97.78, "en": "hmm it's happened to me not only one not only two but many times", "vi": "hmm điều đó đã xảy ra với mình không chỉ một, không chỉ hai mà rất nhiều lần" },
  { "start": 97.89, "end": 102.1, "en": "and I think it's the opportunities of the universe", "vi": "và mình nghĩ đó là những cơ hội của vũ trụ" },
  { "start": 102.1, "end": 106.56, "en": "he or she wants to talk to me hey boy", "vi": "họ muốn nói với mình rằng này chàng trai" },
  { "start": 106.56, "end": 111.08, "en": "it's time you're ready ready to step outside your comfort zone", "vi": "đã đến lúc bạn sẵn sàng bước ra khỏi vùng an toàn" },
  { "start": 111.08, "end": 116.82, "en": "and do something miracle do something better for your life do something", "vi": "và làm điều gì đó kỳ diệu, làm điều gì đó tốt hơn cho cuộc sống của bạn, làm điều gì đó" },
  { "start": 116.82, "end": 120.47, "en": "that you really want deep bird inside", "vi": "mà bạn thực sự muốn sâu thẳm bên trong" },
  { "start": 120.47, "end": 125.7, "en": "but gosh I'm afraid I think I need to wrap up my head", "vi": "nhưng trời ơi mình sợ, mình nghĩ mình cần phải tập hợp lại suy nghĩ" },
  { "start": 125.7, "end": 129.2, "en": "a lot of thinking in me a lot of thoughts", "vi": "rất nhiều suy nghĩ trong mình, rất nhiều tư tưởng" },
  { "start": 129.2, "end": 130.88, "en": "I think I need to observe that", "vi": "mình nghĩ mình cần phải quan sát điều đó" },
  { "start": 131.08, "end": 132.48, "en": "thank you for watching", "vi": "cảm ơn bạn đã xem" },
  { "start": 132.48, "end": 134.56, "en": "see you later in the next video", "vi": "hẹn gặp lại các bạn ở video tiếp theo" },
  { "start": 134.56, "end": 138.99, "en": "have a good day peace", "vi": "chúc một ngày tốt lành, tạm biệt" }
]
;
